let list = [
  {
    name: "건담",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "건캐논",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "건탱크",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "G 파이터",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "볼",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "볼 샤크마우스 버전",
    genre: "기동전사 건담: MS IGLOO",
    grade: "UC",
  },
  {
    name: "볼 제08소대 ver.",
    genre: "기동전사 건담: 제MS08소대",
    grade: "UC",
  },
  {
    name: "볼 ver.ka",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "짐",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "육전형 짐",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "자쿠 I",
    genre: "기동전사 건담",
    grade: "UC",
    tag: "구형 자쿠, 구 자쿠",
  },
  {
    name: "자쿠 I 스나이퍼 타입",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "람바 랄 전용 자쿠 I",
    genre: "기동전사 건담",
    grade: "UC",
    tag: "람바 랄 전용 구형 자쿠, 람바 랄 전용 구 자쿠",
  },
  {
    name: "검은삼연성 전용 자쿠 I",
    genre: "기동전사 건담",
    grade: "UC",
    tag: "검은삼연성 전용 구형 자쿠, 검은삼연성 전용 구 자쿠",
  },
  {
    name: "주다",
    genre: "기동전사 건담: MS IGLOO",
    grade: "UC",
    tag: "즈다",
  },
  {
    name: "자쿠 II",
    genre: "기동전사 건담",
    grade: "UC",
    tag: "자쿠 2",
  },
  {
    name: "자쿠 캐논",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "자쿠 II F2",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "샤아 전용 자쿠 II",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "검은삼연성 전용 자쿠 II",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "가르마 자비 전용 자쿠 II",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "신 마츠나가 전용 자쿠 II",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "구프",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "구프 커스텀",
    genre: "기동전사 건담: 제MS08소대",
    grade: "UC",
  },
  {
    name: "앗가이",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "즈고크",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "샤아 전용 즈고크",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "곡그",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "족그",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "걍",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "돔",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "겔구그",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "겔구그 캐논",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "샤아 전용 겔구그",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "조니 라이덴 전용 겔구그",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "지옹",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "블루 데스티니 1호기",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "블루 데스티니 2호기",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "블루 데스티니 3호기",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "이프리트 카이",
    genre: "기동전사 건담",
    grade: "UC",
    tag: "이프리트 개",
  },
  {
    name: "풀 아머 건담",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "건담 트리스탄",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "퍼펙트 건담",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "G-3 건담",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "건담 4호기",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "건담 5호기",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "풀 아머 건담 7호기",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "엘메스",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "사라미스 사라미스급 순양함",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "마젤란 마젤란급 전함",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "빅잠",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "그라브로",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "자쿠레로",
    genre: "기동전사 건담",
    grade: "UC",
    tag: "자크레로",
  },
  {
    name: "앗잠",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "미데아 미데아급 수송기",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "무사이 무사이급 경순양함",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "파르멜 무사이급 경순양함",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "가우",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "화이트 베이스",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "비그로",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "코어 부스터",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "돕 파이터",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "가르마 전용 돕 파이터",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "건페리",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "도다이 YS",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "G 파이터",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "마젤라 어택",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "61식 전차",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "짐 커맨드 콜로니 타입",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
  },
  {
    name: "짐 커맨드 우주형",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
  },
  {
    name: "짐 한랭지형",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
  },
  {
    name: "건담 NT-1 알렉스",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
  },
  {
    name: "자쿠 II FZ",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
    tag: "자쿠 개, 자쿠改",
  },
  {
    name: "캠퍼",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
  },
  {
    name: "즈고크E",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
  },
  {
    name: "하이곡그",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
  },
  {
    name: "짐 스나이퍼 II",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
    tag: "짐 스나이퍼 2",
  },
  {
    name: "겔구그 예거",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
  },
  {
    name: "릭돔 II",
    genre: "기동전사 건담 0080: 주머니속의 전쟁",
    grade: "UC",
    tag: "릭돔 2",
  },
  {
    name: "건담 GP01 제피랜서스",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
    tag: "건담 GP01 제피랜더스",
  },
  {
    name: "건담 GP01 풀 버니언",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "건담 GP02 사이살리스",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
    tag: "건담 GP02 사이사라스",
  },
  {
    name: "건담 GP03 스테이맨",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "짐 커스텀",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "짐 쿠엘",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "파워드 짐",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "짐 캐논 II",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
    tag: "짐 캐논 2",
  },
  {
    name: "드라체",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "짐 스나이퍼 II",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
    tag: "짐 스나이퍼 2",
  },
  {
    name: "겔구그 마리네",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "시마 전용 겔구그 마리네",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "돔 트로펜",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "가베라 테트라라",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "건담 GP04 가베라",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "덴드로비움",
    genre: "기동전사 건담 0083: 스타더스트 메모리",
    grade: "UC",
  },
  {
    name: "뉴 건담",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "뉴 건담 HWS(헤비 웨폰 시스템)",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "하이뉴 건담",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "사자비",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "나이팅게일",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "제간",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "리가지",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
    tag: "리 가지, 리 가즈이",
  },
  {
    name: "기라 도가",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "레즌 전용 기라 도가",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "퀘스 전용 야크트 도가",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "규네이 전용 야크트 도가",
    genre: "기동전사 건담: 역습의 샤아",
    grade: "UC",
  },
  {
    name: "크시 건담",
    genre: "기동전사 건담: 섬광의 하사웨이",
    grade: "UC",
    tag: "크사이 건담",
  },
  {
    name: "페넬로페",
    genre: "기동전사 건담: 섬광의 하사웨이",
    grade: "UC",
  },
  {
    name: "멧사 타입-F01",
    genre: "기동전사 건담: 섬광의 하사웨이",
    grade: "UC",
  },
  {
    name: "시난주",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "시난주 스타인",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "네오 지옹",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "유니콘 건담",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "풀 아머 유니콘 건담",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "유니콘 건담 2호기 밴시",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "유니콘 건담 2호기 노른",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "유니콘 건담 3호기 페넥스",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "로젠 줄루",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "기라 줄루",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "안젤로 전용 기라 줄루",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "제주르",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "델타 플러스",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "리젤",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "드라이센 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "제간 에코즈 사양",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "이프리트 슈나이드",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "즈사 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "크샤트리아",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "도벤 울프 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "마라사이 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "욤 커크스 전용 자쿠 I 스나이퍼",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "89식 베이스 자바",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "제스타",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "안크샤",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "바이아란 커스텀",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "리젤 대장기",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "네모 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "제타 플러스 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "델타 건담",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "스타크 제간",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "제스타 캐논",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "로토 (로토 트윈)",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "실버 불릿릿",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "실버 불릿릿 서프레서",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "악그 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "쥬악그 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "조고크 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "구스타프 칼 유니콘 Ver.",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "내러티브 건담",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "스트룸 갈루스",
    genre: "기동전사 건담 UC",
    grade: "UC",
  },
  {
    name: "건담 에어리얼",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "건담 르브리스",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "건담 르브리스 손",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "건담 르브리스 울",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "미카엘리스",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "베귀르베우",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "베귀르판테",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "건담 파렉트",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "건담 슈바르제테",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "수성의 마녀 신상품 B(임시)",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "데미 바딩",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "하인드리 슈투름",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "딜란자 솔",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "조워트 헤비",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "데미 트레이너",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "데미 트레이너 추추 기",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "다릴 바르데",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "딜란자 (일반 / 라우더 전용)",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "하인드리",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "틱발랑",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "조워트",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "미라소울사제 플라이트 유닛 장비",
    genre: "기동전사 건담 수성의 마녀",
    grade: "UC",
  },
  {
    name: "바이아란",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "레긴레이즈 줄리에타 전용기",
    genre: "기동전사 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "슈발베 커스텀 시클라제 기",
    genre: "기동전사 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "윙 건담 스카이 제로",
    genre: "건담 브레이커 배틀로그",
    grade: "비우주세기",
  },
  {
    name: "블레이징 건담",
    genre: "건담 브레이커 배틀로그",
    grade: "비우주세기",
  },
  {
    name: "건담 헬리오스",
    genre: "건담 브레이커 배틀로그",
    grade: "비우주세기",
  },
  {
    name: "건담 리브랑스 헤븐",
    genre: "건담 브레이커 배틀로그",
    grade: "비우주세기",
  },
  {
    name: "제노아스 II",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-FX",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-2 다크 하운드",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-1 노멀",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-2 노멀",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-3 노멀",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 레길리스",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-2 더블불릿",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-1 풀 글랜서",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "G-사이포스",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "G-바운서",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "G-엑세스",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-1 타이터스",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "제노아스",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "아델 (디바 컬러)",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "제노아스 커스텀",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "제다스",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "바쿠토",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "도라도",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-3 포트레스",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-1 스팔로",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "파르시아",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "샬돌 카이",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "다나진",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-3 오비탈",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담 AGE-3 포트레스",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "기라르가",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "G-엑세스 잭엣지",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "빌드 부스터",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "건담 X 마오",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
    tag: "건담 X 마왕",
  },
  {
    name: "빌드 부스터 마크 II",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "빌드 건담 마크 II",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "메테오 호퍼",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "캠퍼 어메이징",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "유니버스 부스터 프라프싀 파워 게이트",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "빌드 스트라이크 건담",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "K9 도그 팩",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "전국 어스트레이 건담",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "빌드 건담 마크 II",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "미스 사자비",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "크로스본 건담 마오",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
    tag: "크로스본 건담 마왕",
  },
  {
    name: "스컬 웨폰",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "구프 R35",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "건담 페니체 리나시타",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "스타 버닝 건담",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "갤럭시 부스터",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "SD 위닝 건담",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "SD 레드 워리어 쿠레나이 무사 어메이징",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "건담 엑시아 다크 매터",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "짐 스나이퍼 K9",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "스타 빌드 스트라이크 건담 프라프스키 윙",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "짐/짐",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "건담 어메이징 엑시아",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "스트라이커 징크스",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "건담 어메이징 레드 워리어",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "건담 페니체",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "치낫가이",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "하이퍼 걍코",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "미세스 로엔그린코",
    genre: "건담 빌드 파이터즈",
    grade: "비우주세기",
  },
  {
    name: "슈퍼 후미나",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "슈퍼 후미나 엑시즈 엔젤 Ver.",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "위닝 후미나",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "Ez-암즈",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "메가시키",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
    tag: "메가식",
  },
  {
    name: "메가라이드 런쳐",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "건담 어메이징 레드 워리어",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "건담 레오파드 다빈치",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 라이트닝 블루",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 스트레이 블랙 & 고양이 코스프레",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 밀크 화이트",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 버닝 레드",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 멍멍화이트 & 강아지 코스프레",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 퓨처 핑크",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 위닝 옐로우",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 차차차 브라운",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 럼펌펌퍼플 & 드럼",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 서프그린 & 기타",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 비터스윗브라운 & 초콜릿",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 소다팝 블루 & 아이스캔디",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 프리티 핑크 & 쁘띠쁘띠가이",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 러스티 오렌지 & 플래카드",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 서페이서 그레이 & 플래카드",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "트라이 버닝 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "건담 Ez-SR",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "트랜전트 건담 글래이셔",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "자쿠 어메이징",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "어메이징 스트라이크 프리덤 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "하이뉴 건담 브레이브",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "라이트닝 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "루나게이저 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "트라이 버닝 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "윙 건담 제로 호노오",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "트랜전트 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "걍슬롯",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "카미키 버닝 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "더블 젯 투",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "건담 슈바르츠 리터",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
    tag: "건담 슈발츠 리터",
  },
  {
    name: "디나이얼 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "파워드 짐 카디건",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "파파가이",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "팬더가이",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "R-갸갸",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "건담 트라이온3",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "S x D x G 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "하이목",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "리버시블 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "크로스본 건담 X1 풀크로스 Ver. GBF",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "건담 디엔드",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "건담 포톈트",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
    tag: "건담 포텐트",
  },
  {
    name: "라이트닝 제타 건담",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "건담 라이트닝 블랙 워리어",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "볼덴 암 암즈",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "자이언트 개틀링",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
  },
  {
    name: "볼리스틱 웨폰",
    genre: "건담 빌드 파이터즈 트라이",
    grade: "비우주세기",
    tag: "발리스틱 웨폰",
  },
  {
    name: "스크램블 건담",
    genre: "건담 빌드 파이터즈 아일랜드 워즈",
    grade: "비우주세기",
  },
  {
    name: "라이트닝 백 웨폰 시스템 마크 III",
    genre: "건담 빌드 파이터즈 아일랜드 워즈",
    grade: "비우주세기",
  },
  {
    name: "베앗가이 P (PRETTY)",
    genre: "건담 빌드 파이터즈 아일랜드 워즈",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 캐릭가이 후미나",
    genre: "건담 빌드 파이터즈 아일랜드 워즈",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 캐릭가이 걍코",
    genre: "건담 빌드 파이터즈 아일랜드 워즈",
    grade: "비우주세기",
  },
  {
    name: "건담 더블오 시아 퀀터",
    genre: "건담 빌드 파이터즈 아일랜드 워즈",
    grade: "비우주세기",
  },
  {
    name: "HGBD GBN 가드 프레임",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "임펄스 건담 랑시에",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "제간 블래스트 마스터",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 지엔 알트론",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "모모카풀",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "머신 라이더",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 에이지II 매그넘",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "GMIII 빔 마스터",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 다이버즈 블루 & 플래카드",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 캐릭가이 모모",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 캐릭가이 사라",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 캐릭가이 아야메",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 하로 베이직 그린",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 하로 슈팅 오렌지",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 하로 디바 레드",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 하로 해피 옐로우",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 하로 컨트롤 블루",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 자쿠레로 하로",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 볼 하로",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 모빌 하로",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 하로 이터널 핑크",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 하로로더",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 하로피터",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "하로프라 모모하로",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "스카이하이 윙스",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "그리모어 레드베레",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "세라비 건담 세헤라자드",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "오거 징크스",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "리오 NPD",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "기라 기라가",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "프톨레마이오스 암즈",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 더블오 다이버 에이스",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "가르발디 리베이크",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "지엔 알트론",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 노네임",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "머신 라이더",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "RX_제로마루",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 더블오 스카이",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 더블오 스카이(하이어 댄 스카이 페이즈)",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "제간 블래스트 마스터",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "임펄스 건담 랑시에",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "임펄스 건담 아크",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 러브 팬텀",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 더블오 다이버 에이스",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 더블오 스카이 HWS 트랜스암 인피니티 모드",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "GBN 가드 프레임",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "모빌돌 사라",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 에이지II 매그넘 SV",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 샤이닝 브레이크",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "HWS & SV 웨폰 세트",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "GBN 베이스 건담",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "RX-제로마루 신기결정",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 자라키엘",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "건담 에이지 II 매그넘",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "",
    genre: "건담 빌드 다이버스",
    grade: "비우주세기",
  },
  {
    name: "HGBD:R 코어 건담2 (티탄즈 컬러)",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "HGBD:R 워돔 포드",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "HGBD:R 엘도라 브루트",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "HGBD:R 뉴 지온 건담",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 저스티스 나이트",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "어스리 건담",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "발키랜더",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "비투 웨폰",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "마스포 웨폰",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "코어 건담",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
    tag: "리얼 타입 컬러 & G3 컬러",
  },
  {
    name: "인 저스티스 웨폰즈",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 젤트잠",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "양산형 지오닉 소드",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "모빌돌 메이",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "쥬피티브 건담",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "아발란체 렉스 버스터",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 테르티움",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "머큐원 유닛",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 G-엘스",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 저스티가이",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 GP 나찰천",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "아루스 어스리 건담",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "유라벤 건담",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "새터닉스 유닛 & 웨폰",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "페이크 뉴 유닛 & 웨폰",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "엑스 발키랜더",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "넵테이트 웨폰 & 유닛",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 트라이 에이지 매그넘",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 더블오 스카이 뫼비우스",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 이지스 나이트",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "어운리제 아머",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "건담 아니마리제",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "리라이징 건담",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "코어 건담2 (G-3 컬러)",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "코어 건담2 (티탄즈 컬러)",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "로드 어스트레이 더블 리베이크",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "트라이 슬래쉬 블레이드",
    genre: "건담 빌드 다이버스 Re:Rise",
    grade: "비우주세기",
  },
  {
    name: "제이드라",
    genre: "기동전사 건담 AGE",
    grade: "비우주세기",
  },
  {
    name: "건담(REVIE)",
    genre: "기동전사 건담",
    grade: "UC",
  },
  {
    name: "스트라이크 건담 (에일 소드 런처)",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "프리덤 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "이지스 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "블리츠 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "듀얼 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "버스터 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "레겐 듀얼 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "프로비던스 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "스트라이크 루즈",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "모빌 바쿠",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "라고우",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "모빌 진",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "모빌 진 인서전트",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "모빌 하이메뉴버",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "모빌 시구",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "모빌 시구 딥 암즈",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "미구엘 전용 모빌 진",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 턴 레드",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "105대거",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "M1 어스트레이",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "저스티스 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "스카이 글래스퍼",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "뫼비우스 제로",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "미티어 유닛",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "스타게이저",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "시빌리언 어스트레이 DSSD커스텀",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 레드 프레임",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 레드 프레임 파워드 레드",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 블루 프레임",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 골드 프레임",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "이클립스 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "캘러미티 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "스트라이크 느와르 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "스타게이저 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "하이페리온 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "레이더 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "포비든 건담",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "드레드노트",
    genre: "기동전사 건담 SEED",
    grade: "비우주세기",
  },
  {
    name: "스트라이크 프리덤 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "자쿠 워리어 라이브 콘서트 Ver.",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "카오스 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "어비스 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "구프 이그니티드 이자크 전용기",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 골드 프레임 아마츠",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "아카츠키 건담 오오와시/시라누이",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "데스티니 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 느와르",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "케르베로스 바쿠 하운드",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "진 타입 하이메뉴버 2",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "무라사메 양산형",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "인피니티 저스티스 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "건담 어스트레이 블루 프레임 D",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "이자크 전용 구프 이그니티드",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "구프 이그니티드 양산기",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "슬로터 대거",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "임펄스 건담 (소드 포스)",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "건너 자쿠 워리어",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "레전드 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "카오스 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "가이아 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "레이 전용 블레이즈 자쿠 팬텀",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "루나마리아 전용 건너 자쿠 워리어",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "자쿠 워리어",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "세이버 건담",
    genre: "기동전사 건담 SEED DESTINY",
    grade: "비우주세기",
  },
  {
    name: "육전형 건담",
    genre: "기동전사 건담: 제MS08소대",
    grade: "UC",
  },
  {
    name: "육전형 짐",
    genre: "기동전사 건담: 제MS08소대",
    grade: "UC",
  },
  {
    name: "짐 스나이퍼",
    genre: "기동전사 건담: 제MS08소대",
    grade: "UC",
  },
  {
    name: "건담 EZ-8",
    genre: "기동전사 건담: 제MS08소대",
    grade: "UC",
  },
  {
    name: "윙 건담",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },

  {
    name: "윙 건담 제로",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "윙 건담 제로 커스텀",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "셴롱 건담",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "건담 데스사이즈 헬 커스텀",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "마그아낙",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "건담 샌드록",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "건담 헤비암즈",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "건담 데스사이즈",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "건담 에피온",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "리오",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "톨기스",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "윙 건담 프로토 제로",
    genre: "신기동전기 건담W",
    grade: "비우주세기",
  },
  {
    name: "크로스본 건담 X1",
    genre: "기동전사 건담 크로스본",
    grade: "UC",
  },
  {
    name: "크로스본 건담 X2",
    genre: "기동전사 건담 크로스본",
    grade: "UC",
  },
  {
    name: "건담 발바토스스",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 발바토스 루프스",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 발바토스 루프스 렉스",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 구시온",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 구시온 리베이크",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 바알",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 마르코시아스",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "그림겔데",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "그레이즈",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "그레이즈 카이",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "줄리에타 전용 레긴레이즈",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "헤키쟈",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "로우에이",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "아스타로트 리나시멘트",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 구시온 리베이크 풀시티",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 아스타로트 오리진",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 비다르",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 키마리스 비다르",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "헬름비게 린카",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 플라우로스",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "레긴레이즈 줄리아",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "그레이즈",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 아스타로트",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 발바토스 제6형태",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 단탈리온",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "류세이고 (유성호)",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 하지로보시",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 그레모리",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "아미다 전용 햐쿠렌",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "맥길리스 전용 슈발베 그레이즈",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 키마리스 트루퍼",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "이오 프레임 시덴",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 아스타로트 리나시멘트",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "건담 아스모데우스",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "지크루네",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "햐쿠리",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "햐쿠렌",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "유고",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "모빌아머 하쉬말",
    genre: "기동전기 건담 철혈의 오펀스",
    grade: "비우주세기",
  },
  {
    name: "자쿠 I",
    genre: "기동전사 건담 썬더볼트",
    grade: "UC",
    tag: "구형 자쿠, 구 자쿠",
  },
  {
    name: "자쿠 II 빅 건",
    genre: "기동전사 건담 썬더볼트",
    grade: "UC",
  },
  {
    name: "짐 (썬더볼트)",
    genre: "기동전사 건담 썬더볼트",
    grade: "UC",
  },
  {
    name: "풀 아머 건담 (썬더볼트)",
    genre: "기동전사 건담 썬더볼트",
    grade: "UC",
  },
  {
    name: "아틀라스 건담 (썬더볼트)",
    genre: "기동전사 건담 썬더볼트",
    grade: "UC",
  },
  {
    name: "고기동형 자쿠 II (사이코 자쿠)",
    genre: "기동전사 건담 썬더볼트",
    grade: "UC",
  },
  {
    name: "육전형 건담 S형 (썬더볼트)",
    genre: "기동전사 건담 썬더볼트",
    grade: "UC",
  },
  {
    name: "건담 디 오리진 Ver.",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "건탱크 초기형",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "건캐논 기동시험형 / 화력시험형",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "짐 인터셉트 커스텀",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "맛슈 전용 모빌워커 01식 후기형",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "자쿠 I",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
    tag: "구형 자쿠, 구 자쿠",
  },
  {
    name: "자쿠 I 키시리아 부대기",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
    tag: "구형 자쿠, 구 자쿠",
  },
  {
    name: "샤아 전용 자쿠 I",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
    tag: "구형 자쿠, 구 자쿠",
  },
  {
    name: "액트 자쿠 키시리아 부대기",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "자쿠 II 타입 C-6/R6",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "샤아 전용 자쿠 II 붉은 햬성 Ver.",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "샤아 전용 자쿠 II",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "오르테가 전용 고기동형 자쿠 II",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "자쿠 II C형/ C-5형",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "자쿠 하프 캐논",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "프로토타입 돔",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "람바 랄 전용 부그",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "자쿠 I 데님/슬렌더 기",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
    tag: "구형 자쿠, 구 자쿠",
  },
  {
    name: "국지형 건담",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "국지형 건담 (북미전선사양)",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "건담 FSD",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "와프",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "프로토타입 구프 전술실증기",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "건캐논 최초기형 철기병중대사양",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "가이아/맛슈 전용 고기동형 자쿠II",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "짐 가드 커스텀",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "건캐논 (쿠쿠르스 도안의 섬 Ver.)",
    genre: "기동전사 건담 The Origin",
    grade: "UC",
  },
  {
    name: "더블오 건담",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "더블오라이저 GN 콘덴서 타입",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "켈딤 건담",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 버체 (바체)",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "마스라오",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 큐리오스",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "티에렌 우주형",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 듀나메스",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "오버 플래그",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "징크스 III 연방군 타입",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "징크스 III",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 아스트레아 타입-F",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "더블오 건담 세븐소드",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 엑시아",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 세츠나 F 세이에이 블루 & 플래카드",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 록온 스트라토스 그린 & 플래카드",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 그라함 에이커 화이트 & 플래카드",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 알렐루야 합티즘 오렌지 & 플래카드",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "쁘띠가이 티에리아 아데 퍼플 & 플래카드",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "퀀터 풀 세이버",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "더블오 건담 세븐소드/G",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 엑시아 리페어 II",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "티에렌 육전형",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "그라함 전용 유니온 플래그 커스텀",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "세라핌 건담",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "징크스",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "티에렌 타오즈",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 스로네 아인",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 쓰로네 쯔바이",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 나드레",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "티에렌 우주지휘관형",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "사세스 전용 이낙트 커스텀",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "이낙트 모의전 컬러",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "어헤드 양산형",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "부시도 전용 어헤드",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "GN아쳐",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "세르게이 전용 티에렌 타오즈",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "가랏조",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "어헤드 스멀트론",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "아르케 건담",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "스사노오",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "오 건담 (실전배치형)",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "힐링 전용 가랏조",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "세라비 건담",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "리본즈 건담",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 아발란체 엑시아 대시",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 아발란체",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "더블오 퀀터",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 샤바나",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 하루트",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "라파엘 건담",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "브레이브 양산형",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "건담 아발란체",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "더블오 잔라이저",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "브레이브 지휘관용 시험기",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "GN 암즈",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "유니온 플래그",
    genre: "기동전사 건담 OO",
    grade: "비우주세기",
  },
  {
    name: "비기나 기나",
    genre: "기동전사 건담 F91",
    grade: "UC",
  },
  {
    name: "비기나 기나 II",
    genre: "기동전사 건담 F91",
    grade: "UC",
  },
  {
    name: "건담 F91",
    genre: "기동전사 건담 F91",
    grade: "UC",
  },
  {
    name: "건담 Mk II",
    genre: "기동전사 Z건담",
    grade: "UC",
    tag: "(마크 2)",
  },
  {
    name: "건담 Mk II 티탄즈 컬러",
    genre: "기동전사 Z건담",
    grade: "UC",
    tag: "(마크 2)",
  },
  {
    name: "제타 건담",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "백식",
    genre: "기동전사 Z건담",
    grade: "UC",
    tag: "햐쿠시키",
  },
  {
    name: "메타스",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "릭디아스",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "크와트로 전용 릭디아스",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "가브스레이",
    genre: "기동전사 Z건담",
    grade: "UC",
    tag: "갸브스레이",
  },
  {
    name: "슈퍼 건담",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "네모",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "사이코 건담",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "멧사라",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "젯 투",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "파라스 아테네",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "함므라비",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "제타 플러스 C1",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "짐 II",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "하이잭 연방군 사양",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "앗시마",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "제크아인 ",
    genre: "기동전사 Z건담",
    grade: "UC",
    tag: "제쿠아인",
  },
  {
    name: "가르발디 베타",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "마라사이",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "바잠",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "갸프랑",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "하만 전용 가자C",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "가자 C",
    genre: "기동전사 Z건담",
    grade: "UC",
  },
  {
    name: "가자 C",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "더블 제타 건담",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "풀 아머 더블 제타 건담",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "플 투 전용 큐베레이 마크 II",
    genre: "기동전사 건담ZZ",
    grade: "UC",
    tag: "마크 2",
  },
  {
    name: "엘피 플 전용 큐베레이 마크 II",
    genre: "기동전사 건담ZZ",
    grade: "UC",
    tag: "마크 2",
  },
  {
    name: "슈츠룸 디아스",
    genre: "기동전사 건담ZZ",
    grade: "UC",
    tag: "슈트룸 디아스",
  },
  {
    name: "바우",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "햄머 햄머",
    genre: "기동전사 건담ZZ",
    grade: "UC",
    tag: "함마 함마",
  },
  {
    name: "FAZZ",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "드라이센",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "도벤 울프",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "아이잭",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "자쿠 마리나",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "큐베레이 마크 II",
    genre: "기동전사 건담ZZ",
    grade: "UC",
    tag: "마크 2",
  },
  {
    name: "자쿠 III 커스텀",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "바우 양산형",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "짐 III",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "R쟈쟈",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "가즈L",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "가즈R",
    genre: "기동전사 건담ZZ",
    grade: "UC",
  },
  {
    name: "빅토리 건담",
    genre: "기동전사 V 건담",
    grade: "UC",
  },
  {
    name: "V2 건담",
    genre: "기동전사 V 건담",
    grade: "UC",
  },
  {
    name: "V 대시 건담",
    genre: "기동전사 V 건담",
    grade: "UC",
  },
  {
    name: "V2 어썰트 버스터 건담",
    genre: "기동전사 V 건담",
    grade: "UC",
  },
  {
    name: "건이지",
    genre: "기동전사 V 건담",
    grade: "UC",
  },
  {
    name: "조로아트",
    genre: "기동전사 V 건담",
    grade: "UC",
  },
  {
    name: "건담 엑스",
    genre: "기동전사 건담 X",
    grade: "비우주세기",
  },
  {
    name: "건담 엑스 디바이더",
    genre: "기동전사 건담 X",
    grade: "비우주세기",
  },
  {
    name: "건담 더블 엑스",
    genre: "기동전사 건담 X",
    grade: "비우주세기",
  },
  {
    name: "건담 에어마스터",
    genre: "기동전사 건담 X",
    grade: "비우주세기",
  },
  {
    name: "갓 건담",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "건담 슈피겔",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "마스터 건담",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "샤이닝 건담",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "풍운재기",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "데스 아미",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "데빌 건담",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "노벨 건담",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "건담 슈피겔",
    genre: "기동무투전 G 건담",
    grade: "비우주세기",
  },
  {
    name: "익스트림 건담",
    genre: "건프라 빌더즈 비기닝 G",
    grade: "비우주세기",
  },
  {
    name: "S 건담",
    genre: "건담 센티넬",
    grade: "UC",
  },
  {
    name: "EX-S 건담",
    genre: "건담 센티넬",
    grade: "UC",
  },
  {
    name: "제타 플러스 A1",
    genre: "건담 센티넬",
    grade: "UC",
  },
  {
    name: "건담 G-아케인",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "우주용 자하남 양산형",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "우주용 자하남 크림 닉 전용기",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "마스크 전용 엘프 브룩",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "마스크 전용기 맥 나이프",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "다하크",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "자스티마",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "건담 G-셀프 퍼펙트 팩 장비형",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "건담 G-셀프 대기권용 팩 장비형",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "건담 G-루시퍼",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "그리모어",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "건담 G-셀프 어설트 팩 장비형",
    genre: "건담 G의 레콘기스타",
    grade: "비우주세기",
  },
  {
    name: "턴 엑스",
    genre: "∀ 건담",
    grade: "비우주세기",
    tag: "턴에이 건담",
  },
  {
    name: "턴에이 건담",
    genre: "∀ 건담",
    grade: "비우주세기",
    tag: "턴에이 건담",
  },
  {
    name: "카풀",
    genre: "∀ 건담",
    grade: "비우주세기",
    tag: "턴에이 건담",
  },
  {
    name: "짐 스트라이커",
    genre: "Advance of Z",
    grade: "UC",
  },
  {
    name: "건담 어드밴스드 헤이즐",
    genre: "Advance of Z",
    grade: "UC",
  },
  {
    name: "건담 운드워트",
    genre: "Advance of Z",
    grade: "UC",
  },
  {
    name: "바잠 (A.O.Z 리부트 Ver.)",
    genre: "Advance of Z",
    grade: "UC",
  },
  {
    name: "레전드BB 무사 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 나이트 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "사탄 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 풀 아머 나이트 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "진무사 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 마룡검사 제로 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 기사 유니콘 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "라이메이 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "현무장 여포 톨기스",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 건담 바쿠신 마루",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "건담 대장군",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 제타 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 건담 Mk-II",
    genre: "건담 무사",
    grade: "비우주세기",
    tag: "무사 건담 마크 2,무사 건담 마크 II",
  },
  {
    name: "무사 ZZ 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 뉴 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 카게 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 카게 Z 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 카게 ZZ 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "카게닌자 샤자쿠",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 2대 건담 대장군",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 돔",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 드라이센",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "암장군",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "자쿠 삼형제",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "신겐 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "켄신 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 무사 빅토리",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 버설 나이트 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 커맨드 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 무사 갓마루",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "질풍의 뉴",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 디오",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "화염의 더블 제타",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "건담 부장군",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "4대 건담 대장군",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 사자비",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "와카 자쿠토",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "밀림의 MK-II",
    genre: "건담 무사",
    grade: "비우주세기",
    tag: "밀림의 마크 2, 밀림의 마크 II, 밀림의 Mk 2, 밀림의 Mk II",
  },
  {
    name: "거산의 사이코",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "번개 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "초대 건담 대장군",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "사자 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "용 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "무사 G 아머",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "하야부사 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "용장비장",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "백룡 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "청룡 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "적룡 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "천생 대장군",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "성룡기 마스 드래곤",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "킹 건담 2세",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "레전드BB 기사 슈페리얼 드래곤",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "버설 나이트 건담",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "기갑신 엘가이야",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "건 제네시스",
    genre: "건담 무사",
    grade: "비우주세기",
  },
  {
    name: "토네이도 건담",
    genre: "SD건담 G제네레이션",
    grade: "비우주세기",
  },
  {
    name: "건담 아쿠아리우스",
    genre: "SD건담 G제네레이션",
    grade: "비우주세기",
  },
  {
    name: "노부나가 건담 에피온",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "서전트 베르데 버스터 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "오공 임펄스 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "벤자민 V2 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "에드워드 세컨드 V",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "워 호스",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "사스케 델타 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "조조 윙 건담 의성의 장",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "오공 임펄스 건담 DX",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "아르센 건담 X",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "서전트 베르데 버스터 건담 DX",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "건담 에피온 다크 마스크 Ver.",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "베르데 버스터 대원",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "궁기 스트라이크 프리덤 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "클레오파틍라 큐베레이 다크 마스크 Ver.",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "제천대성 오공 임펄스 건담 -투전승불-",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "용준유비 유니콘 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "아서 건담 Mk-II",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
    tag: "아서 건담 마크 2, 아서 건담 마크 II, 아서 건담 Mk 2,아서 건담 Mk II",
  },
  {
    name: "시저 레전드 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "로빈후드 건담 에이지2",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "나이트 스트라이크 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "손권 어스트레이 혁염상호",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "워 호스 나이트 월드 Ver.",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "사이조 건담 델타 카이",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "워록 이지스 건담",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "샤인 그래스퍼 드래곤",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "레이프 건담 GP04",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "히어로즈 신상품B (임시)",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "슈페리얼 스트라이크 프리덤 드래곤",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "조운 더블오 건담 커맨드",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "다크 그래스퍼 드래곤",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "손권 어스트레이 혁염상호",
    genre: "SD건담 월드 히어로즈",
    grade: "비우주세기",
  },
  {
    name: "유비 유니콘 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "관우 뉴건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "장비 갓 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "조조 윙 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "손견 건담 어스트레이",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "동탁 프로비던스 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "초선 크샤트리아",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "여포 시난주 & 적토마",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "조운 더블오 건담 & 벽룡구",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "마초 건담 발바토스",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "트리니티 바이크",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "손권 건담 어스트레이",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "황충 건담 듀나메스",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "장합 알트론 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "하후돈 톨기스 III",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
    tag: "하후돈 톨기스 3",
  },
  {
    name: "하로",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "손책 건담 어스트레이",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "태사자 듀얼 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "하후연 톨기스",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "손상향 스트라이크 루즈",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "제갈량 프리덤 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "장료 사자비",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "주유 아카츠키",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "사마의 데스티니 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "순욱 스트라이크 느와르",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "전위 마스터 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "서황 건담 데스사이즈",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "대교 건담 아르테미",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "소교 GN 아쳐",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "천패 조조 윙 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "감녕 크로스본 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "염황 장비 갓 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },
  {
    name: "무성 관우 뉴 건담",
    genre: "SD건담 월드 삼국창걸전",
    grade: "비우주세기",
  },

  {
    name: "",
    genre: "기동전사 건담",
    grade: "UC",
  },
];
